name: 'setup arduino-cli and platform'
description: 'install platform into arduino-cli to be ready to compile'
inputs:
  boardurl:  
    description: 'URL of arduino compatible package.json'
    required: false
    default: ''
  platform:  
    description: 'platform name(s), which should be installed'
    required: true
    default: 'arduino:avr'
    
runs:
  using: "composite"
  steps: 
    - name: Prepare platform installation
      run: arduino-cli core update-index ${{ inputs.boardurl }}
      shell: bash
    - name: Install platform 
      run: arduino-cli core install ${{ inputs.platform }} ${{ inputs.boardurl }}
      shell: bash
    - name: install pyserial
      run: |
        if [ ${{ inputs.platform }} == "esp32:esp32" ]
        then
          pip install pyserial
        fi;
      shell: bash
